import { computed, ref, watch } from 'vue'

type Language = 'es' | 'en'
type Theme = 'light' | 'dark'

type Dictionary = Record<string, string>

const dictionaries: Record<Language, Dictionary> = {
  es: {
    skip_content: 'Ir al contenido principal',
    skip_nav: 'Ir a la navegacion',
    skip_footer: 'Ir al pie de pagina',
    nav_home: 'Inicio',
    nav_faq: 'Preguntas frecuentes',
    nav_player: 'Reproductor',
    nav_aria: 'Navegacion principal',
    theme_to_light: 'Cambiar a modo claro',
    theme_to_dark: 'Cambiar a modo oscuro',
    lang_button_es: 'Espanol',
    lang_button_en: 'English',
    player_title: 'Lista de reproduccion',
    player_list_aria: 'Lista de canciones',
    player_add_button: 'Agregar',
    player_add_folder_button: 'Agregar carpeta',
    player_clear_button: 'Limpiar',
    player_unknown_artist: 'Artista desconocido',
    player_remove_song: 'Eliminar cancion',
    player_empty_title: 'La lista de reproduccion está vacia',
    player_empty_copy: 'Agregue archivos multimedia a la lista de reproduccion',
    player_select_files: 'Seleccionar archivos multimedia',
    player_upload_hint: 'Agrega canciones por lotes desde el boton Agregar o selecciona archivos de audio.',
    player_audio_missing: 'La cancion activa no tiene audio. Agrega un archivo desde el modal para reproducir.',
    intro_title: 'SOBELO: Reproductor de Musica en Linea',
    intro_copy: 'Un reproductor multimedia en linea centrado en privacidad, ejecutado en su navegador.',
    intro_features: 'Caracteristicas Principales',
    intro_how_to: 'Como Usar',
    intro_feature_1_title: 'Privacidad primero',
    intro_feature_1_copy: 'Todos los archivos se reproducen en tu dispositivo, sin subir contenido a servidores.',
    intro_feature_2_title: 'Formatos comunes',
    intro_feature_2_copy: 'Compatibilidad con MP3, FLAC, WAV y OGG para uso local rapido. En FLAC y OGG, la reproduccion puede variar segun el navegador.',
    intro_feature_3_title: 'Sin instalacion',
    intro_feature_3_copy: 'Abre, agrega canciones y reproduce inmediatamente desde el navegador.',
    intro_feature_4_title: 'Controles fluidos',
    intro_feature_4_copy: 'Volumen, progreso, cambio de pista y modo de repeticion en una sola vista.',
    intro_step_1: 'Pulsa Agregar cancion y selecciona un archivo de audio.',
    intro_step_2: 'Organiza la playlist y elige una pista desde la lista.',
    intro_step_3: 'Controla reproduccion, volumen y progreso desde el panel principal.',
    faq_heading: 'Preguntas Frecuentes',
    faq_1_q: 'Es SOBELO gratuito?',
    faq_1_a: 'Si. SOBELO es 100% gratuito. No hay costos ocultos ni limites de uso.',
    faq_2_q: 'Mi privacidad esta protegida?',
    faq_2_a: 'Absolutamente. Tus archivos se procesan localmente en tu navegador y no se suben a nuestros servidores.',
    faq_3_q: 'Que formatos se admiten?',
    faq_3_a: 'Soporta MP3, FLAC, WAV y OGG para audio local. La disponibilidad de FLAC/OGG depende del navegador.',
    modal_title: 'Agregar cancion',
    modal_label_title: 'Titulo',
    modal_label_artist: 'Artista',
    modal_label_audio: 'Archivo de audio',
    modal_label_cover: 'Imagen de portada',
    modal_label_position: 'Posicion',
    modal_label_index: 'Indice',
    modal_pos_start: 'Al inicio',
    modal_pos_end: 'Al final',
    modal_pos_index: 'En posicion especifica',
    modal_cancel: 'Cancelar',
    modal_add: 'Agregar',
    modal_error_required: 'Titulo y artista son obligatorios.',
    modal_error_index: 'El indice debe ser un numero entero mayor o igual a 0.',
    modal_error_audio_extension: 'Formato de archivo no permitido. Use MP3, FLAC, WAV u OGG.',
    modal_error_audio_mime: 'El tipo MIME del archivo no coincide con MP3, FLAC, WAV u OGG.',
    modal_error_audio_size: 'El archivo es demasiado grande. Maximo permitido: {maxMb} MB.',
    modal_error_add: 'No se pudo agregar la cancion.',
    footer_copy: '(c) 2026 SOBELO. Todos los derechos reservados.',
    footer_privacy: 'Politica de privacidad',
    footer_terms: 'Terminos de servicio',
    footer_github: 'GitHub',
    privacy_back_home: 'Volver al inicio',
    footer_disclaimer: 'SOBELO no aloja ni almacena archivos multimedia. Todo el contenido se procesa localmente en el navegador.',
    privacy_title: 'Politica de privacidad',
    privacy_updated: 'Ultima actualizacion: febrero 8, 2026',
    privacy_section_1_title: '1. Introduccion',
    privacy_section_1_p1: 'Bienvenido a SOBELO. Valoramos su privacidad y nos comprometemos a proteger su informacion personal.',
    privacy_section_1_p2: 'Esta politica de privacidad explica como recopilamos, usamos, almacenamos y protegemos su informacion cuando utiliza nuestros servicios.',
    privacy_section_1_p3: 'Al usar nuestros servicios, acepta los terminos de esta politica de privacidad.',
    privacy_section_2_title: '2. Recopilacion de informacion',
    privacy_section_2_intro: 'Los tipos de informacion que recopilamos incluyen:',
    privacy_section_2_item_1: 'Informacion del dispositivo: tipo de navegador, sistema operativo y direccion IP.',
    privacy_section_2_item_2: 'Datos de uso: como utiliza nuestros servicios.',
    privacy_section_2_item_3: 'Archivos locales: los archivos multimedia que elige reproducir (procesados solo en su dispositivo, no cargados a nuestros servidores).',
    privacy_section_3_title: '3. Uso de la informacion',
    privacy_section_3_intro: 'Usamos la informacion recopilada para:',
    privacy_section_3_item_1: 'Proporcionar y mejorar las funciones de nuestros servicios.',
    privacy_section_3_item_2: 'Analizar el uso de los servicios para optimizar la experiencia del usuario.',
    privacy_section_3_item_3: 'Asegurar la seguridad y estabilidad del servicio.',
    privacy_section_3_item_4: 'Cumplir con requisitos legales y regulatorios.',
    privacy_section_4_title: '4. Almacenamiento de la informacion',
    privacy_section_4_intro: 'Metodos de almacenamiento de datos:',
    privacy_section_4_item_1: 'La mayor parte del procesamiento de datos se realiza en su dispositivo local.',
    privacy_section_4_item_2: 'Usamos medidas tecnicas seguras para proteger los datos almacenados.',
    privacy_section_4_item_3: 'Los periodos de retencion de datos se determinan segun las necesidades del servicio y los requisitos legales.',
    privacy_section_4_item_4: 'Puede solicitar la eliminacion de sus datos personales en cualquier momento.',
    privacy_section_5_title: '5. Compartir informacion',
    privacy_section_5_intro: 'No vendemos su informacion personal. Podemos compartir informacion en las siguientes circunstancias:',
    privacy_section_5_item_1: 'Con su consentimiento explicito.',
    privacy_section_5_item_2: 'Para cumplir con obligaciones legales u ordenes judiciales.',
    privacy_section_5_item_3: 'Para proteger nuestros derechos, propiedad o seguridad.',
    privacy_section_5_item_4: 'Con proveedores de servicios de confianza de terceros (como servicios publicitarios).',
    privacy_section_6_title: '6. Servicios publicitarios',
    privacy_section_6_intro: 'Este sitio web utiliza servicios publicitarios de terceros como Google AdSense para mostrar anuncios. Estos servicios pueden:',
    privacy_section_6_item_1: 'Usar cookies y tecnologias similares para recopilar informacion.',
    privacy_section_6_item_2: 'Mostrar anuncios personalizados basados en sus intereses.',
    privacy_section_6_item_3: 'Compartir cierta informacion con otros sitios web para mejorar la efectividad de los anuncios.',
    privacy_section_6_ads_link_label: 'Puede gestionar sus preferencias publicitarias desde:',
    privacy_section_6_note: 'Nota: esta seccion contiene informacion especifica sobre servicios publicitarios.',
    privacy_section_7_title: '7. Uso de cookies',
    privacy_section_7_intro: 'Usamos cookies y tecnologias similares para recordar sus preferencias y analizar el uso del sitio web.',
    privacy_section_7_item_1: 'Proporcionar contenido y anuncios personalizados.',
    privacy_section_7_item_2: 'Asegurar el funcionamiento adecuado del sitio web. Puede gestionar las preferencias de cookies desde la configuracion de su navegador.',
    privacy_section_8_title: '8. Servicios de terceros',
    privacy_section_8_p1: 'Podemos usar servicios de terceros como Google Analytics, Google AdSense y servicios CDN.',
    privacy_section_8_p2: 'Estos servicios tienen sus propias politicas de privacidad, y le recomendamos revisar sus respectivas politicas.',
    privacy_section_9_title: '9. Sus derechos',
    privacy_section_9_intro: 'Tiene los siguientes derechos:',
    privacy_section_9_item_1: 'Derecho de acceso: saber que informacion hemos recopilado sobre usted.',
    privacy_section_9_item_2: 'Derecho de rectificacion: solicitar la correccion de informacion personal inexacta.',
    privacy_section_9_item_3: 'Derecho de eliminacion: solicitar la eliminacion de su informacion personal.',
    privacy_section_9_item_4: 'Derecho a la limitacion del tratamiento: limitar nuestro tratamiento de su informacion personal.',
    privacy_section_9_item_5: 'Derecho a la portabilidad de datos: obtener sus datos en un formato estructurado.',
    privacy_section_10_title: '10. Contactenos',
    privacy_section_10_contact: 'Contactenos: contact@sobelo.om',
    privacy_section_10_p2: 'Le responderemos lo antes posible despues de recibir su solicitud.',
    privacy_section_11_title: '11. Cambios en la politica',
    privacy_section_11_p1: 'Podemos actualizar esta politica de privacidad de vez en cuando.',
    privacy_section_11_p2: 'Los cambios importantes se le comunicaran por medios apropiados.',
    privacy_section_11_p3: 'Le recomendamos revisar esta politica regularmente para mantenerse informado. El uso continuo de nuestros servicios indica su aceptacion de la politica actualizada.',
    privacy_section_11_p4: 'Si tiene preguntas sobre esta politica de privacidad, por favor contactenos: contact@sobelo.om',
    terms_title: 'Terminos de servicio',
    terms_updated: 'Ultima actualizacion: febrero 8, 2026',
    terms_section_1_title: '1. En resumen',
    terms_section_1_p1: 'Proveemos estas herramientas para su uso personal y no comercial. Al usarlas, acepta nuestras reglas.',
    terms_section_1_p2: 'Por favor, no use indebidamente el servicio, no copie nuestros materiales ni intente romper el sistema.',
    terms_section_1_p3: 'El servicio se proporciona tal cual, y nuestra responsabilidad es limitada como se detalla a continuacion.',
    terms_section_2_title: '2. Introduccion',
    terms_section_2_p1: 'Bienvenido a SOBELO. Estos Terminos de Servicio rigen su acceso y uso de nuestro sitio web y servicios.',
    terms_section_2_p2: 'Al utilizar el servicio, acepta estar sujeto a estos terminos.',
    terms_section_3_title: '3. Como puede usar SOBELO',
    terms_section_3_intro: 'Le otorgamos una licencia limitada para usar las herramientas de SOBELO para fines personales y no comerciales. Bajo esta licencia, no debe:',
    terms_section_3_item_1: 'Modificar, copiar o redistribuir nuestro software, codigo, imagenes y otros materiales.',
    terms_section_3_item_2: 'Usar los materiales para fines comerciales o para exhibicion publica.',
    terms_section_3_item_3: 'Intentar descompilar o aplicar ingenieria inversa a nuestro software.',
    terms_section_3_item_4: 'Eliminar avisos de derechos de autor.',
    terms_section_3_item_5: 'Transferir los materiales a otra persona o reflejarlos en otro servidor.',
    terms_section_3_p2: 'Si viola estas reglas, su licencia para usar el servicio puede ser cancelada en cualquier momento.',
    terms_section_4_title: '4. Sus responsabilidades',
    terms_section_4_intro: 'Acepta usar nuestro servicio de manera responsable y legal. Especificamente, se compromete a no:',
    terms_section_4_item_1: 'Violar ninguna ley o regulacion.',
    terms_section_4_item_2: 'Dañar o explotar a menores de ninguna manera.',
    terms_section_4_item_3: 'Enviar spam u otra publicidad no solicitada.',
    terms_section_4_item_4: 'Hacerse pasar por nuestra empresa, nuestro personal u otros usuarios.',
    terms_section_4_item_5: 'Interferir con el uso o disfrute del servicio por parte de cualquier otra persona.',
    terms_section_5_title: '5. Propiedad intelectual',
    terms_section_5_p1: 'Nuestro servicio y todo su contenido original, caracteristicas y funcionalidades son y seguiran siendo propiedad exclusiva de SOBELO y sus licenciantes, protegidos por leyes internacionales de derechos de autor y marcas registradas.',
    terms_section_5_p2: 'No puede usar nuestra marca o imagen comercial sin nuestro consentimiento previo por escrito.',
    terms_section_6_title: '6. Exenciones de responsabilidad y servicio tal cual',
    terms_section_6_p1: 'Nuestro servicio se proporciona tal cual, sin garantias. No prometemos que sera perfecto, siempre disponible o adecuado para necesidades especificas.',
    terms_section_6_p2: 'No ofrecemos otras garantias, expresas o implicitas, con respecto a la fiabilidad o idoneidad del servicio para un proposito particular.',
    terms_section_7_title: '7. Limitacion de responsabilidad',
    terms_section_7_p1: 'En la maxima medida permitida por la ley, SOBELO no sera responsable de daños indirectos, incidentales o consecuentes derivados de su uso o incapacidad para usar nuestro servicio.',
    terms_section_8_title: '8. Enlaces a terceros',
    terms_section_8_p1: 'Nuestro servicio puede contener enlaces a sitios web de terceros que no son de nuestra propiedad ni estan bajo nuestro control. No somos responsables del contenido o las practicas de esos sitios.',
    terms_section_9_title: '9. Legislacion aplicable',
    terms_section_9_p1: 'Estos terminos se regiran por las leyes de la jurisdiccion en la que se basa nuestra empresa, sin tener en cuenta disposiciones sobre conflictos de leyes.',
    terms_section_10_title: '10. Cambios en estos terminos',
    terms_section_10_p1: 'Podemos modificar estos terminos en cualquier momento. Le notificaremos cambios relevantes. Al continuar usando el servicio tras la entrada en vigor de revisiones, acepta los nuevos terminos.',
    terms_section_11_title: '11. Contactenos',
    terms_section_11_contact: 'Contactenos: contact@sobelo.om',
    control_favorite: 'Favorito',
    control_prev: 'Anterior',
    control_play: 'Reproducir',
    control_pause: 'Pausar',
    control_next: 'Siguiente',
    control_shuffle: 'Mezclar',
    control_repeat: 'Cambiar repeticion',
    control_notice_empty_list: 'No hay canciones en la lista.',
    control_notice_missing_audio: 'Esta cancion no tiene archivo de audio.',
    control_notice_play_failed: 'No se pudo reproducir el audio.',
    control_notice_browser_unsupported: 'Tu navegador no soporta la reproduccion de audio requerida por la aplicacion.',
    control_notice_format_unsupported: 'Este formato no es compatible con tu navegador para reproduccion.',
    control_notice_audio_corrupt: 'El archivo de audio parece estar dañado o incompleto.',
    control_notice_audio_load_failed: 'No se pudo cargar el archivo de audio.'
  },
  en: {
    skip_content: 'Skip to main content',
    skip_nav: 'Skip to navigation',
    skip_footer: 'Skip to footer',
    nav_home: 'Home',
    nav_faq: 'FAQ',
    nav_player: 'Player',
    nav_aria: 'Main navigation',
    theme_to_light: 'Switch to light mode',
    theme_to_dark: 'Switch to dark mode',
    lang_button_es: 'Spanish',
    lang_button_en: 'English',
    player_title: 'Playlist',
    player_list_aria: 'Song list',
    player_add_button: 'Add',
    player_add_folder_button: 'Add folder',
    player_clear_button: 'Clear',
    player_unknown_artist: 'Unknown artist',
    player_remove_song: 'Remove song',
    player_empty_title: 'Your playlist is empty',
    player_empty_copy: 'Add media files to start listening',
    player_select_files: 'Select media files',
    player_upload_hint: 'Add songs in batches from the Add button or select audio files.',
    player_audio_missing: 'The active song has no audio file. Add one from the modal to play it.',
    intro_title: 'SOBELO: Online Music Player',
    intro_copy: 'A privacy-first online media player that runs directly in your browser.',
    intro_features: 'Key features',
    intro_how_to: 'How to use',
    intro_feature_1_title: 'Privacy first',
    intro_feature_1_copy: 'All files are played on your device, without uploading content to servers.',
    intro_feature_2_title: 'Common formats',
    intro_feature_2_copy: 'Support for MP3, FLAC, WAV and OGG for fast local usage. FLAC and OGG playback may vary by browser.',
    intro_feature_3_title: 'No installation',
    intro_feature_3_copy: 'Open, add songs and play instantly in your browser.',
    intro_feature_4_title: 'Smooth controls',
    intro_feature_4_copy: 'Volume, progress, track switch and repeat mode in one view.',
    intro_step_1: 'Tap Add song and select an audio file.',
    intro_step_2: 'Organize the playlist and choose a track from the list.',
    intro_step_3: 'Control playback, volume and progress from the main panel.',
    faq_heading: 'Frequently asked questions',
    faq_1_q: 'Is SOBELO free?',
    faq_1_a: 'Yes. SOBELO is 100% free. There are no hidden costs or usage limits.',
    faq_2_q: 'Is my privacy protected?',
    faq_2_a: 'Absolutely. Your files are processed locally in your browser and never uploaded to our servers.',
    faq_3_q: 'Which formats are supported?',
    faq_3_a: 'Supports MP3, FLAC, WAV and OGG for local playback. FLAC/OGG availability depends on browser support.',
    modal_title: 'Add song',
    modal_label_title: 'Title',
    modal_label_artist: 'Artist',
    modal_label_audio: 'Audio file',
    modal_label_cover: 'Cover image',
    modal_label_position: 'Position',
    modal_label_index: 'Index',
    modal_pos_start: 'At start',
    modal_pos_end: 'At end',
    modal_pos_index: 'At specific index',
    modal_cancel: 'Cancel',
    modal_add: 'Add',
    modal_error_required: 'Title and artist are required.',
    modal_error_index: 'Index must be an integer greater than or equal to 0.',
    modal_error_audio_extension: 'Unsupported file extension. Use MP3, FLAC, WAV or OGG.',
    modal_error_audio_mime: 'The file MIME type does not match MP3, FLAC, WAV or OGG.',
    modal_error_audio_size: 'The file is too large. Maximum allowed: {maxMb} MB.',
    modal_error_add: 'Could not add the song.',
    footer_copy: '(c) 2026 SOBELO. All rights reserved.',
    footer_privacy: 'Privacy policy',
    footer_terms: 'Terms of service',
    footer_github: 'GitHub',
    privacy_back_home: 'Back to home',
    footer_disclaimer: 'SOBELO does not host or store media files. All content is processed locally in your browser.',
    privacy_title: 'Privacy policy',
    privacy_updated: 'Last updated: January 1, 2025',
    privacy_section_1_title: '1. Introduction',
    privacy_section_1_p1: 'Welcome to SOBELO. We value your privacy and are committed to protecting your personal information.',
    privacy_section_1_p2: 'This privacy policy explains how we collect, use, store and protect your information when you use our services.',
    privacy_section_1_p3: 'By using our services, you accept the terms of this privacy policy.',
    privacy_section_2_title: '2. Information collection',
    privacy_section_2_intro: 'The types of information we collect include:',
    privacy_section_2_item_1: 'Device information: browser type, operating system and IP address.',
    privacy_section_2_item_2: 'Usage data: how you use our services.',
    privacy_section_2_item_3: 'Local files: media files you choose to play (processed only on your device, not uploaded to our servers).',
    privacy_section_3_title: '3. Use of information',
    privacy_section_3_intro: 'We use collected information to:',
    privacy_section_3_item_1: 'Provide and improve our service features.',
    privacy_section_3_item_2: 'Analyze service usage to optimize the user experience.',
    privacy_section_3_item_3: 'Ensure service security and stability.',
    privacy_section_3_item_4: 'Comply with legal and regulatory requirements.',
    privacy_section_4_title: '4. Data storage',
    privacy_section_4_intro: 'Data storage methods include:',
    privacy_section_4_item_1: 'Most data processing is performed on your local device.',
    privacy_section_4_item_2: 'We use secure technical measures to protect stored data.',
    privacy_section_4_item_3: 'Data retention periods are determined by service needs and legal requirements.',
    privacy_section_4_item_4: 'You may request deletion of your personal data at any time.',
    privacy_section_5_title: '5. Information sharing',
    privacy_section_5_intro: 'We do not sell your personal information. We may share information under these circumstances:',
    privacy_section_5_item_1: 'With your explicit consent.',
    privacy_section_5_item_2: 'To comply with legal obligations or court orders.',
    privacy_section_5_item_3: 'To protect our rights, property or safety.',
    privacy_section_5_item_4: 'With trusted third-party service providers (such as advertising services).',
    privacy_section_6_title: '6. Advertising services',
    privacy_section_6_intro: 'This website uses third-party advertising services such as Google AdSense to display ads. These services may:',
    privacy_section_6_item_1: 'Use cookies and similar technologies to collect information.',
    privacy_section_6_item_2: 'Display personalized ads based on your interests.',
    privacy_section_6_item_3: 'Share certain information with other websites to improve ad effectiveness.',
    privacy_section_6_ads_link_label: 'You can manage your ad preferences at:',
    privacy_section_6_note: 'Note: this section includes specific information about advertising services.',
    privacy_section_7_title: '7. Use of cookies',
    privacy_section_7_intro: 'We use cookies and similar technologies to remember your preferences and analyze website usage.',
    privacy_section_7_item_1: 'Provide personalized content and ads.',
    privacy_section_7_item_2: 'Ensure proper website operation. You can manage cookie preferences through your browser settings.',
    privacy_section_8_title: '8. Third-party services',
    privacy_section_8_p1: 'We may use third-party services such as Google Analytics, Google AdSense and CDN services.',
    privacy_section_8_p2: 'These services have their own privacy policies, and we recommend reviewing them.',
    privacy_section_9_title: '9. Your rights',
    privacy_section_9_intro: 'You have the following rights:',
    privacy_section_9_item_1: 'Right of access: know what information we have collected about you.',
    privacy_section_9_item_2: 'Right of rectification: request correction of inaccurate personal information.',
    privacy_section_9_item_3: 'Right of deletion: request deletion of your personal information.',
    privacy_section_9_item_4: 'Right to restrict processing: limit our processing of your personal information.',
    privacy_section_9_item_5: 'Right to data portability: obtain your data in a structured format.',
    privacy_section_10_title: '10. Contact us',
    privacy_section_10_contact: 'Contact us: contact@sobelo.om',
    privacy_section_10_p2: 'We will respond as soon as possible after receiving your request.',
    privacy_section_11_title: '11. Policy changes',
    privacy_section_11_p1: 'We may update this privacy policy from time to time.',
    privacy_section_11_p2: 'Important changes will be communicated through appropriate channels.',
    privacy_section_11_p3: 'We recommend reviewing this policy regularly to stay informed. Continued use of our services indicates acceptance of the updated policy.',
    privacy_section_11_p4: 'If you have questions about this privacy policy, please contact us: contact@sobelo.com',
    terms_title: 'Terms of service',
    terms_updated: 'Last updated: January 1, 2025',
    terms_section_1_title: '1. In summary',
    terms_section_1_p1: 'We provide these tools for personal and non-commercial use. By using them, you agree to our rules.',
    terms_section_1_p2: 'Please do not misuse the service, copy our materials, or attempt to break the system.',
    terms_section_1_p3: 'The service is provided as is, and our liability is limited as described below.',
    terms_section_2_title: '2. Introduction',
    terms_section_2_p1: 'Welcome to SOBELO. These Terms of Service govern your access to and use of our website and services.',
    terms_section_2_p2: 'By using the service, you agree to be bound by these terms.',
    terms_section_3_title: '3. How you may use SOBELO',
    terms_section_3_intro: 'We grant you a limited license to use SOBELO tools for personal and non-commercial purposes. Under this license, you must not:',
    terms_section_3_item_1: 'Modify, copy or redistribute our software, code, images or other materials.',
    terms_section_3_item_2: 'Use the materials for commercial purposes or public display.',
    terms_section_3_item_3: 'Attempt to decompile or reverse engineer our software.',
    terms_section_3_item_4: 'Remove copyright notices.',
    terms_section_3_item_5: 'Transfer materials to another person or mirror them on another server.',
    terms_section_3_p2: 'If you violate these rules, your license to use the service may be terminated at any time.',
    terms_section_4_title: '4. Your responsibilities',
    terms_section_4_intro: 'You agree to use our service responsibly and lawfully. Specifically, you agree not to:',
    terms_section_4_item_1: 'Violate any law or regulation.',
    terms_section_4_item_2: 'Harm or exploit minors in any way.',
    terms_section_4_item_3: 'Send spam or other unsolicited advertising.',
    terms_section_4_item_4: 'Impersonate our company, staff or other users.',
    terms_section_4_item_5: 'Interfere with any other person use or enjoyment of the service.',
    terms_section_5_title: '5. Intellectual property',
    terms_section_5_p1: 'Our service and all original content, features and functionality are and will remain the exclusive property of SOBELO and its licensors, protected by international copyright and trademark laws.',
    terms_section_5_p2: 'You may not use our brand or trade dress without prior written consent.',
    terms_section_6_title: '6. Disclaimers and as-is service',
    terms_section_6_p1: 'Our service is provided as is, without warranties. We do not promise it will be perfect, always available, or suitable for your specific needs.',
    terms_section_6_p2: 'We make no other warranties, express or implied, regarding reliability or fitness for a particular purpose.',
    terms_section_7_title: '7. Limitation of liability',
    terms_section_7_p1: 'To the maximum extent permitted by law, SOBELO is not liable for indirect, incidental, or consequential damages arising from your use of or inability to use our service.',
    terms_section_8_title: '8. Third-party links',
    terms_section_8_p1: 'Our service may include links to third-party websites that are not owned or controlled by us. We are not responsible for the content or practices of those websites.',
    terms_section_9_title: '9. Governing law',
    terms_section_9_p1: 'These terms are governed by the laws of the jurisdiction where our company is based, without regard to conflict of law provisions.',
    terms_section_10_title: '10. Changes to these terms',
    terms_section_10_p1: 'We may modify these terms at any time. We will notify you of relevant changes. Continued use of the service after revisions take effect means you accept the updated terms.',
    terms_section_11_title: '11. Contact us',
    terms_section_11_contact: 'Contact us: contact@sobelo.om',
    control_favorite: 'Favorite',
    control_prev: 'Previous',
    control_play: 'Play',
    control_pause: 'Pause',
    control_next: 'Next',
    control_shuffle: 'Shuffle',
    control_repeat: 'Toggle repeat',
    control_notice_empty_list: 'No songs in the playlist.',
    control_notice_missing_audio: 'This song does not have an audio file.',
    control_notice_play_failed: 'Could not play audio.',
    control_notice_browser_unsupported: 'Your browser does not support the required audio playback features.',
    control_notice_format_unsupported: 'This format is not supported for playback in your browser.',
    control_notice_audio_corrupt: 'The audio file appears to be corrupted or incomplete.',
    control_notice_audio_load_failed: 'Could not load the audio file.'
  }
}

const language = ref<Language>('es')
const theme = ref<Theme>('light')

let initialized = false

function initialize(): void {
  if (initialized || typeof window === 'undefined') {
    return
  }

  const storedLang = window.localStorage.getItem('lang')
  const storedTheme = window.localStorage.getItem('theme')

  if (storedLang === 'es' || storedLang === 'en') {
    language.value = storedLang
  }

  if (storedTheme === 'light' || storedTheme === 'dark') {
    theme.value = storedTheme
  }

  initialized = true
}

function toggleLanguage(): void {
  language.value = language.value === 'es' ? 'en' : 'es'
}

function toggleTheme(): void {
  theme.value = theme.value === 'light' ? 'dark' : 'light'
}

function t(key: string): string {
  return dictionaries[language.value][key] ?? key
}

watch(language, (next) => {
  if (typeof document !== 'undefined') {
    document.documentElement.lang = next
  }

  if (typeof window !== 'undefined') {
    window.localStorage.setItem('lang', next)
  }
}, { immediate: true })

watch(theme, (next) => {
  if (typeof document !== 'undefined') {
    document.body.setAttribute('data-theme', next)
  }

  if (typeof window !== 'undefined') {
    window.localStorage.setItem('theme', next)
  }
}, { immediate: true })

export function useUiPreferences() {
  initialize()

  return {
    language: computed(() => language.value),
    theme: computed(() => theme.value),
    toggleLanguage,
    toggleTheme,
    t
  }
}
